#!/bin/bash
### ---
### name: 'consensus_generation (3)'
### outputs:
### - 'barcode14.consensus.fa'
### - 'barcode14.tmp.fa'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf -- $exit_status > /home/etudiant/fatemeh/hbv_pipeline/work/22/3f43b4c2a383d061f17a77d61c9ce8/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/etudiant/fatemeh/hbv_pipeline/work/22/3f43b4c2a383d061f17a77d61c9ce8/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f sequence.fasta
    rm -f barcode14.sorted.vcf.gz
    rm -f barcode14.sorted.vcf.gz.tbi
    rm -f barcode14.sorted.coverage.bed
    ln -s /home/etudiant/fatemeh/hbv_pipeline/Ref/sequence.fasta sequence.fasta
    ln -s /home/etudiant/fatemeh/hbv_pipeline/work/a6/81dcbda6cc68cd195ef6454304b4fe/barcode14.sorted.vcf.gz barcode14.sorted.vcf.gz
    ln -s /home/etudiant/fatemeh/hbv_pipeline/work/a6/81dcbda6cc68cd195ef6454304b4fe/barcode14.sorted.vcf.gz.tbi barcode14.sorted.vcf.gz.tbi
    ln -s /home/etudiant/fatemeh/hbv_pipeline/work/f8/d4208686fe118f6688ab5c398336b4/barcode14.sorted.coverage.bed barcode14.sorted.coverage.bed
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/etudiant/fatemeh/hbv_pipeline/work/22/3f43b4c2a383d061f17a77d61c9ce8/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
