---
title: "Rapport QC & Mapping HBV"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(readr)
library(stringr)
##library(tidyr)
library(plotly)
source("scripts_r/fonctions_globales.R")

base_dir <- "src/results"
barcodes <- sprintf("barcode%02d", 1:16)
plots <- generate_all_qc_plots(base_dir, barcodes)


## 1. Composition en GC (raw)
```{r}
plots$gc_raw
```

## 2. Longueur des reads (raw)
```{r}
plots$length_raw
```

## 3. Score qualité (Phred) raw
```{r}
plots$phred_raw
```

## 4. Score Phred par position (raw)
```{r}
plots$phred_par_pos_raw
```

## 5.  Composition GC des reads alignés
```{r}
plots$gc_mapped
```

## 6. % Reads mappés vs unmappés
```{r}
plots$reads_mapped_prop
```

## 7. Longueur reads mappés vs unmappés
```{r}
plots$length_mapped
```

##8. Score qualité du mapping
```{r}
plots$map_score
```

##9. Score Phred des reads mappés
```{r}
plots$phred_mapped
```

##10. Heatmap couverture/profondeur
```{r}
plots$coverage_heatmap
```

##11. Tableau de pourcentage de couverture
```{r}
knitr::kable(
  plots$coverage_summary,
  caption = "Pourcentage de couverture par barcode",
  digits  = 1
)
```